#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorI2CCustom)
#pragma config(Sensor, S4,     UltraSonic,     sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     lift2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motor4,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "JoystickDriver.c"
#include "drivers/hitechnic-irseeker-v2.h"

void StopMotors() {
	motor[motor1] = 0;
	motor[motor2] = 0;
	motor[motor3] = 0;
	motor[motor4] = 0;
}
void mount() {
		// Mount the ring
	motor[lift2] = 20;
	wait1Msec(1500);
	motor[lift2] = 0;

	motor[motor1] = -20;
	motor[motor2] = 20;
	motor[motor3] = 20;
	motor[motor4] = -20;
	wait1Msec(300);
	StopMotors();

}

task main() {
	int distance;
	int IRDir;
	int goodDistance = 7;    // Note: US distance is in cm (?)
	int distanceThreshold = 2;
	int goodSpeed = 25;
	bool something = false;
	bool IRset = false;
	bool distanceSet = false;
	// Move to position

	motor[motor1] = -30;
	motor[motor2] = 30;
	motor[motor3] = 30;
	motor[motor4] = -30;
	wait1Msec(1000);
	StopMotors();

	motor[motor1] = -20;
	motor[motor2] = -20;
	motor[motor3] = -20;
	motor[motor4] = -20;
	wait1Msec(1000);
	StopMotors();

	while (true) {
		alive();
		// Read sensor inputs
		distance = SensorValue[UltraSonic];
		IRDir = HTIRS2readACDir(IRSeeker);
		// Check for input errors
		if (IRDir == -1) {
			// IR error occured
			// Loudest77
			nVolume = 4;
			PlaySound(soundException);
			nVolume = 2;
			return;
		}
		else if (IRDir >= 1 || IRDir < 5) {
				// move left a bit
			motor[motor1] = goodSpeed;
			motor[motor2] = goodSpeed;
			motor[motor3] = -goodSpeed;
			motor[motor4] = -goodSpeed;
		}
		else if (IRDir > 5 || IRDir <= 9) {
				// move right a bit
			motor[motor1] = -goodSpeed;
			motor[motor2] = -goodSpeed;
			motor[motor3] = goodSpeed;
			motor[motor4] = goodSpeed;
		}
		else if (IRDir == 5) {
			IRset = true;
			StopMotors();
		}

		if (distance < 0 || distance > 255) {
			// US error occured
			nVolume = 4;
			PlaySound(soundException);
			nVolume = 2;
			return;
		}
		else if (distance == 255) {
			// US range error (nonfatal)
			nVolume = 2;
			PlaySound(soundException);
		}
		else if (distance > (goodDistance + distanceThreshold)) {
			//move forward
			motor[motor1] = -goodSpeed;
			motor[motor2] = goodSpeed;
			motor[motor3] = goodSpeed;
			motor[motor4] = -goodSpeed;
		}
		else if (distance < (goodDistance - distanceThreshold)) {
				//move back
			motor[motor1] = goodSpeed;
			motor[motor2] = -goodSpeed;
			motor[motor3] = -goodSpeed;
			motor[motor4] = goodSpeed;
		}
		else if (distance >= (goodDistance - distanceThreshold) && distance <= (goodDistance + distanceThreshold)) {
			distanceSet = true;
			StopMotors();
		}

		if (distanceSet == true && IRset == true) {
			// Now mount the donut!
			StopMotors();
			eraseDisplay();
			nxtDisplayCenteredTextLine(4, "Mount the ring!");
			if (something == false) {
				mount();
				something = true;
			}
		}
	}
}
