#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     lift2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motor4,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    armExt,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/*
Joystick 1 is driving
Joystick 2 is arm control
*/
int scaler = 6;

void drive() {
	// Joystick values are 8 bit signed ints (-127 to 128)
	// 1: 3
  // 2: 2.5
  // 3: 2
	// 4: 1
	int button = joystick.joy1_Buttons;
	int button2 = joystick.joy2_Buttons;
	//nxtDisplayBigStringAt(4, 31, "%d", button);
	short rotate = 0;
	short preciseY = 0;
	short preciseX = 0;
	float scalerlift1 = 1;
	float scalerlift2 = 1;
	int servoChange = 5;

	switch (button) {
		case 1:
			scaler = 6;
			break;
		case 2:
			scaler = 4;
			break;
		case 4:
			scaler = 2;
			break;
		case 8:
			scaler = 1;
			break;
		case 64:
			rotate = 100 / scaler;
			break;
		case 128:
			rotate = -(100 / scaler);
			break;
	}

	switch (button2) {
		case 8:
			preciseY = 20;
			break;
		case 2:
			preciseY = -20;
			break;
		case 4:
			preciseX = 20;
		case 1:
			preciseX = -20;
		case 64:
			scalerlift1 = 1.3;
			break;
		case 128:
			scalerlift2 = 1.3;
			break;
		case 16:
			// Lower servo
			if (servo[armExt] >= 0){
				int currentArmExt = ServoValue[armExt];
				servo[armExt] = currentArmExt - servoChange;
			}
			break;
		case 32:
			// Raise servo
			if (servo[armExt] <= 360){
				int currentArmExt = ServoValue[armExt];
				servo[armExt] = currentArmExt + servoChange;
			}
			break;
	}

	short driveX = joystick.joy1_x2 / scaler;
	short driveY = joystick.joy1_y1 / scaler;
	short lift1Power = joystick.joy2_y1 / (1 * scalerlift1);
	short lift2Power = joystick.joy2_y2 / (4 * scalerlift2);

//	short rotate = joystick.joy1_x2 / scaler;

	int threshold = 8;

	// Driving power thresholds
	if (!(driveX > threshold || driveX < -threshold)) {
		driveX = 0;
	}
	if (!(driveY > threshold || driveY < -threshold)) {
		driveY = 0;
	}
	if (!(rotate > threshold || rotate < -threshold)) {
		rotate = 0;
	}
	// Lift power thresholds
	if (!(lift1Power > threshold || lift1Power < -threshold)) {
		lift1Power = 0;
	}
	if (!(lift2Power > threshold || lift2Power < -threshold)) {
		lift2Power = 0;
	}

	if (preciseY != 0) {
		motor[motor1] = -preciseY + -preciseX;
		motor[motor2] = preciseY + -preciseX;
		motor[motor3] = -(-preciseY + -preciseX);
		motor[motor4] = -(preciseY + -preciseX);
	}
	else {
		motor[motor1] = -driveY + -driveX + rotate;
		motor[motor2] = driveY + -driveX + rotate;
		motor[motor3] = -(-driveY + -driveX + -rotate);
		motor[motor4] = -(driveY + -driveX + -rotate);
	}
	motor[lift1] = lift1Power;
	motor[lift2] = lift2Power;
}

task main() {
	waitForStart();
	servoChangeRate[armExt] = 1;
	while (true) {
		getJoystickSettings(joystick);
		drive();
		alive();
	}
}
