#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     Distance,       sensorSONAR)
#pragma config(Motor,  motorA,          touchExt,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     lift1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     lift2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motor4,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    armExt,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"

// Robot is done moving when at 125 cm
task main() {
	waitForStart();

	int IRDir;
	int power = 30;
	int servoPos = 100;

	// Config code
	bFloatDuringInactiveMotorPWM = false;
	nVolume = 4;
	servo[armExt] = servoPos;
	// Lift arm in order to clear the ground
	motor[lift1] = 90;
	wait1Msec(1000);
	motor[lift1] = 0;

	while (true) {
		// Move to plate position

		servo[armExt] = servoPos;
		motor[motor1] = -power;
		motor[motor2] = power;
		motor[motor3] = power;
		motor[motor4] = -power;

		if (SensorValue[Distance] >= 254 || SensorValue[Distance] < 1) {
			// Range error or sensor not plugged in
			PlaySound(soundException);
			continue;
		}
		if (SensorValue[Distance] >= 125) {
			// Break loop and continue to next part
			motor[motor1] = 0;
			motor[motor2] = 0;
			motor[motor3] = 0;
			motor[motor4] = 0;
			break;
		}
	}
	servo[armExt] = servoPos;
	// Rotate to peg 45 degrees
	motor[motor1] = power;
	motor[motor2] = power;
	motor[motor3] = power;
	motor[motor4] = power;
	wait1Msec(380);

	servo[armExt] = servoPos;
	motor[motor1] = 0;
	motor[motor2] = 0;
	motor[motor3] = 0;
	motor[motor4] = 0;
	int IRErrorCount = 0;
	while (IRDir != 5) {
		servo[armExt] = servoPos;
		IRDir = HTIRS2readACDir(HTIRS2);
		if (IRDir == 0 || IRDir == -1) {
			// IR detect error
			PlaySound(soundException);
			IRErrorCount++;
			if (IRErrorCount > 5) {
				ClearSounds();
				PlaySound(soundBeepBeep);
				//return;
			}
		}
		else {
			IRErrorCount = 0;
		}

		if (IRDir > 5) {
			// Peg is to the right
			motor[motor1] = power;
			motor[motor2] = power;
			motor[motor3] = -power;
			motor[motor4] = -power;
		}
		if (IRDir < 5) {
			// Peg is to the left
			motor[motor1] = -power;
			motor[motor2] = -power;
			motor[motor3] = power;
			motor[motor4] = power;
		}
	}
	motor[motor1] = 0;
	motor[motor2] = 0;
	motor[motor3] = 0;
	motor[motor4] = 0;
	// In position to put the ring on
	// Move the Lift2 up to second peg level
	servo[armExt] = servoPos;

	motor[lift2] = 40;
	wait1Msec(1000);
	motor[lift2] = 0;

	// Move forward and put on peg
	servo[armExt] = servoPos;
	motor[motor1] = -power;
	motor[motor2] = power;
	motor[motor3] = power;
	motor[motor4] = -power;
	wait1Msec(900);
	servo[armExt] = servoPos;
	motor[motor1] = 0;
	motor[motor2] = 0;
	motor[motor3] = 0;
	motor[motor4] = 0;

	motor[lift2] = -20;
	servo[armExt] = servoPos;
	wait1Msec(1000);
	motor[lift2] = 0;

	// Play the sweet sound of victory (or failure)
	PlaySound(soundUpwardTones);
}
