#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorNormal, openLoop, encoder)
#pragma config(Motor, mtr_S1_C2_1, lift1, tmotorNormal, openLoop, encoder)
#pragma config (Motor, mtr_S1_C2_2, lift2, tmotorNormal, openLoop, encoder)

#include "JoystickDriver.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//TJoystick joystick
//THESE ARE THE STARTING POSITIONS OF THE SERVOS. PLEASE, PLEASE MAKE SURE THEY
//ARE RIGHT. PLEASE, AGAIN.

//Okay, for these: Count and Counter control the delay on the Arm, and Count2 and Counter2 control the claw's Delay
// THese are necessary because if you just let it run without a delay, the controller picks up too many increments
// and it moves from one end to the other. This way it changes rather nicely.



void JoystickOneOp()
{

motor[leftMotor] = joystick.joy1_y1;
motor[rightMotor]= joystick.joy1_y2;
motor[lift1] =     joystick.joy2_y1;
motor[lift2] =     joystick.joy2_y2;


  //IF you click button 1, the car does a 90 degree right turn
  /*if(button == 1){
     nMotorEncoder[leftMotor] = 0;
    nMotorEncoder[rightMotor] = 0;
    while(nMotorEncoder[leftMotor] <1600){
        motor[leftMotor]  = 40;
        motor[rightMotor] = -40;
      }
        motor[leftMotor]  = 0;
        motor[rightMotor] = 0;
  }
  */
  //IF you click button 2, the car drives forward steadily
  /*if( button == 2){

        motor[leftMotor]  = -40;
        motor[rightMotor] = -40;

}
*/
}
/*
void JoystickTwoOp()
{
  int Button;
  int ArmDrive;
  int ClawDrive;
  //This is inputting the values from the joystick # 2, for the button, joystick1 Y axis, and joystick 2 Y axis;
  Button = joystick.joy2_Buttons;
  ArmDrive = joystick.joy2_y1;
  ClawDrive = joystick.joy2_y2;
  //Here we move the Arm servo, if the joystick is up (value greater than 0) we increment by 1
  //if the joystick is down (value less than one) we decrement by 1.
  if(ArmDrive > 20 && !Count)
  {
    ArmPosition += 1;
    servo[ArmServo] = ArmPosition;
    Count = true;
    if(ArmPosition > 240){
      ArmPosition = 240;
    }
      ArmPosition2 -= 1;
    servo[ArmServo2] = ArmPosition2;
    if(ArmPosition2 < 15){
      ArmPosition = 15;
  }
  }
 else if(ArmDrive < -20 && !Count)
  {
    ArmPosition -= 1;
    servo[ArmServo] = ArmPosition;
    Count = true;
     if(ArmPosition < 10){
      ArmPosition = 10;
    }
      ArmPosition2 += 1;
    servo[ArmServo2] = ArmPosition2;
     if(ArmPosition2  > 245){
      ArmPosition2 = 245;
  }
  }


//Here we move the Claw servo, if the joystick is up (value greater than 0) we increment by 1
  //if the joystick is down (value less than one) we decrement by 1.
if(ClawDrive < -100 && !Count2)
    {
    ClawPosition += 5;
    servo[ClawServo] = ClawPosition;
    Count2 = true;
     if(ArmPosition > 250){
      ArmPosition = 250;
    }
   }
  else if(ClawDrive > 100 && !Count2)
    {
    ClawPosition -= 5;
    servo[ClawServo] = ClawPosition;
    Count2 = true;
     if(ArmPosition < 10){
      ArmPosition = 10;
    }
    }

    //Here, we move the dump servos based on the 8 and 7 buttons
    if(Button == 1)
    {
      //CHECK THESE NUMBERS PLEASE. PLEASE.
      servo[DumpLeft] = 195;
      servo[DumpRight] = 60;
    }
    if(Button == 2)
    {
      servo[DumpLeft] = LdumpPosition;
      servo[DumpRight] = RdumpPosition;
    }
 return;
}
*/
task main() {
/*{

   initializeServos();
  while (true)
  {
    getJoystickSettings(joystick);
    JoystickOneOp();
    JoystickTwoOp();
    // This is the delay counter for the arm control
    if(Count){
      Counter ++;
    }
    if(Counter > 30){
    Count = false;
    Counter = 0;
    }
    //and here's the delay counter for the claw control
     if(Count2){
      Counter2 ++;
    }
    if(Counter2 > 30){
    Count2 = false;
    Counter2 = 0;
    }
   nxtDisplayTextLine(3, "Servo: %d", nMotorEncoder[leftMotor]);
  }
  */

 JoystickOneOp();

}
